/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.project.gui;

import com.project.enums.ItemTypeEnum;
import com.project.flyweight.RCMGUIHelperFlyweight;
import com.project.gui.mediator.GUIImageHelper;
import com.project.gui.mediator.GUIRCMHelper;
import com.project.gui.renderers.ImageTextTableRenderer;
import com.project.gui.renderers.ImagesNText;
import com.project.models.RCM;
import com.project.models.RecyclableItemTransaction;
import com.project.models.RecyclableItemTransaction.RecyclableItemTransactionBuilder;

import javax.swing.*;
import java.awt.*;
import java.util.Date;
import java.util.Objects;

public class RecyclableMachineGUI extends javax.swing.JFrame {
    final GUIRCMHelper rcmHelper;
    private final String machineId;
    private final String groupId;


    //model
    DefaultListModel dm = new DefaultListModel();
    private javax.swing.JPanel dashBoardPanel;
    private javax.swing.JLabel ecoreLogo;
    private javax.swing.JTextField enterWeightField;
    private javax.swing.JTable itemTypeTable;
    private javax.swing.JComboBox<String> itemTypeToRecycleSelectionBox;
    private javax.swing.JTable metricsTable;
    private javax.swing.JPanel moneyCouponSelection;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JPanel recycleItemsSelection;
    private javax.swing.JComboBox<String> rewardSelection;
    private javax.swing.JToggleButton showInLbsButton;
    private javax.swing.JToggleButton showInkgsButton;
    private javax.swing.JTable showItemTypeTable;
    private javax.swing.JPanel showSelectedList;
    private javax.swing.JLabel showTotalPriceLabel;
    private javax.swing.JLabel totalPriceOfDroppedItemsLabel;
    private javax.swing.JLabel welcomeLabel;
    private javax.swing.JPanel welcomePanel;

    public RecyclableMachineGUI(RCM rcm) {

        this.machineId = rcm.getMachineId();
        this.groupId = rcm.getGroupId();
        RCMGUIHelperFlyweight facadeFlyweight = RCMGUIHelperFlyweight.getInstance();
        rcmHelper = facadeFlyweight.getRCMGUIHelper(machineId);
        initComponents();
        ecoreLogo.setIcon(GUIImageHelper.getScaledLogoImage(ecoreLogo.getWidth(), ecoreLogo.getHeight()));
        removeAllPanels();
        welcomePanel.setVisible(true);
        welcomeLabel.setText(String.format("Welcome to %s", machineId));

    }

    private void initTable() {
        itemTypeTable.setModel(rcmHelper.getItemTypesModel());
        metricsTable.setModel(rcmHelper.getMetricsTableModel());
        itemTypeTable.setAutoCreateRowSorter(true);
        itemTypeTable.setDefaultRenderer(ImagesNText.class, new ImageTextTableRenderer());
        rcmHelper.populateItemTypeTable();
        rcmHelper.populateMetricsTable();
    }

    private void removeAllPanels() {
        dashBoardPanel.setVisible(false);
        welcomePanel.setVisible(false);
        recycleItemsSelection.setVisible(false);
        showSelectedList.setVisible(false);
        moneyCouponSelection.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroup buttonGroup1 = new ButtonGroup();
        JPanel mainPanel = new JPanel();
        JPanel topPanel = new JPanel();
        ecoreLogo = new javax.swing.JLabel();
        JPanel bodyPanel = new JPanel();
        JPanel bodyTopPanel = new JPanel();
        JToggleButton dashBoardButton = new JToggleButton();
        JToggleButton recycleItemsButton = new JToggleButton();
        JToggleButton cancelAddingItemsButton = new JToggleButton();
        JPanel bodyBodyPanel = new JPanel();
        dashBoardPanel = new javax.swing.JPanel();
        JScrollPane jScrollPane2 = new JScrollPane();
        itemTypeTable = new javax.swing.JTable();
        JScrollPane jScrollPane3 = new JScrollPane();
        metricsTable = new javax.swing.JTable();
        welcomePanel = new javax.swing.JPanel();
        welcomeLabel = new javax.swing.JLabel();
        recycleItemsSelection = new javax.swing.JPanel();
        itemTypeToRecycleSelectionBox = new javax.swing.JComboBox<>();
        JLabel itemTypeSlectionLabel = new JLabel();
        enterWeightField = new javax.swing.JTextField();
        JLabel enterWeightLabel = new JLabel();
        /**
         * @param args the command line arguments
         */
        // Variables declaration - do not modify//GEN-BEGIN:variables
        JButton addMoreItemsButton = new JButton();
        JButton submitButton = new JButton();
        showSelectedList = new javax.swing.JPanel();
        JScrollPane jScrollPane1 = new JScrollPane();
        showItemTypeTable = new javax.swing.JTable();
        showInkgsButton = new javax.swing.JToggleButton();
        JLabel totalValueLabel = new JLabel();
        JToggleButton addMoreItemsGoBack = new JToggleButton();
        JToggleButton getRewardButton = new JToggleButton();
        showTotalPriceLabel = new javax.swing.JLabel();
        showInLbsButton = new javax.swing.JToggleButton();
        moneyCouponSelection = new javax.swing.JPanel();
        JLabel selectValueTitle = new JLabel();
        JLabel totalPriceOfDroppedItemsTitle = new JLabel();
        totalPriceOfDroppedItemsLabel = new javax.swing.JLabel();
        rewardSelection = new javax.swing.JComboBox<>();
        JToggleButton submitReward = new JToggleButton();
        JPanel outputPanel = new JPanel();
        outputLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recycling Machine");
        setAutoRequestFocus(false);
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setName("Recycling Machine"); // NOI18N

        mainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        mainPanel.setMaximumSize(new java.awt.Dimension(680, 540));
        mainPanel.setMinimumSize(new java.awt.Dimension(680, 540));
        mainPanel.setPreferredSize(new java.awt.Dimension(680, 540));
        mainPanel.setLayout(new java.awt.BorderLayout());

        topPanel.setBackground(new java.awt.Color(1, 87, 155));
        topPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        topPanel.setMaximumSize(new java.awt.Dimension(680, 100));
        topPanel.setMinimumSize(new java.awt.Dimension(680, 100));
        topPanel.setPreferredSize(new java.awt.Dimension(680, 100));

        ecoreLogo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ecoreLogo.setMaximumSize(new java.awt.Dimension(400, 90));
        ecoreLogo.setMinimumSize(new java.awt.Dimension(400, 90));
        ecoreLogo.setPreferredSize(new java.awt.Dimension(400, 90));
        ecoreLogo.setRequestFocusEnabled(false);

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topPanelLayout.createSequentialGroup()
                                .addGap(171, 171, 171)
                                .addComponent(ecoreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        topPanelLayout.setVerticalGroup(
                topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(topPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ecoreLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(topPanel, java.awt.BorderLayout.PAGE_START);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bodyPanel.setMaximumSize(new java.awt.Dimension(680, 380));
        bodyPanel.setMinimumSize(new java.awt.Dimension(680, 380));
        bodyPanel.setPreferredSize(new java.awt.Dimension(680, 380));
        bodyPanel.setLayout(new java.awt.BorderLayout());

        bodyTopPanel.setBackground(new java.awt.Color(51, 153, 255));
        bodyTopPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bodyTopPanel.setMaximumSize(new java.awt.Dimension(680, 40));
        bodyTopPanel.setMinimumSize(new java.awt.Dimension(680, 40));
        bodyTopPanel.setPreferredSize(new java.awt.Dimension(680, 40));

        dashBoardButton.setText("DashBoard");
        dashBoardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashBoardButtonClicked(evt);
            }
        });

        recycleItemsButton.setText("Recycle Items");
        recycleItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recycleItemsButtonClicked(evt);
            }
        });

        cancelAddingItemsButton.setText("Cancel adding Items");
        cancelAddingItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelAddingItemsButtonClick(evt);
            }
        });

        javax.swing.GroupLayout bodyTopPanelLayout = new javax.swing.GroupLayout(bodyTopPanel);
        bodyTopPanel.setLayout(bodyTopPanelLayout);
        bodyTopPanelLayout.setHorizontalGroup(
                bodyTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bodyTopPanelLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(dashBoardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(recycleItemsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelAddingItemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                                .addContainerGap())
        );
        bodyTopPanelLayout.setVerticalGroup(
                bodyTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bodyTopPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bodyTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dashBoardButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(recycleItemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(cancelAddingItemsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        bodyPanel.add(bodyTopPanel, java.awt.BorderLayout.NORTH);

        bodyBodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyBodyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bodyBodyPanel.setMaximumSize(new java.awt.Dimension(680, 320));
        bodyBodyPanel.setMinimumSize(new java.awt.Dimension(680, 320));
        bodyBodyPanel.setLayout(new java.awt.CardLayout(5, 5));

        dashBoardPanel.setBackground(new java.awt.Color(102, 204, 255));
        dashBoardPanel.setMaximumSize(new java.awt.Dimension(680, 310));
        dashBoardPanel.setMinimumSize(new java.awt.Dimension(680, 310));
        dashBoardPanel.setPreferredSize(new java.awt.Dimension(670, 310));

        itemTypeTable.setRowHeight(30);
        itemTypeTable.setRowMargin(5);
        jScrollPane2.setViewportView(itemTypeTable);

        metricsTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{

                },
                new String[]{

                }
        ));
        jScrollPane3.setViewportView(metricsTable);

        javax.swing.GroupLayout dashBoardPanelLayout = new javax.swing.GroupLayout(dashBoardPanel);
        dashBoardPanel.setLayout(dashBoardPanelLayout);
        dashBoardPanelLayout.setHorizontalGroup(
                dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addGroup(dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(136, Short.MAX_VALUE))
        );
        dashBoardPanelLayout.setVerticalGroup(
                dashBoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(dashBoardPanelLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        bodyBodyPanel.add(dashBoardPanel, "card2");

        welcomePanel.setBackground(new java.awt.Color(102, 204, 255));
        welcomePanel.setMaximumSize(new java.awt.Dimension(680, 310));
        welcomePanel.setMinimumSize(new java.awt.Dimension(680, 310));
        welcomePanel.setPreferredSize(new java.awt.Dimension(680, 310));

        welcomeLabel.setFont(new java.awt.Font("Comic Sans MS", Font.BOLD, 24)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
                welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 681, Short.MAX_VALUE)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                                        .addContainerGap(124, Short.MAX_VALUE)
                                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(204, Short.MAX_VALUE)))
        );
        welcomePanelLayout.setVerticalGroup(
                welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 320, Short.MAX_VALUE)
                        .addGroup(welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, welcomePanelLayout.createSequentialGroup()
                                        .addContainerGap(114, Short.MAX_VALUE)
                                        .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(152, Short.MAX_VALUE)))
        );

        bodyBodyPanel.add(welcomePanel, "card3");

        recycleItemsSelection.setBackground(new java.awt.Color(102, 204, 255));
        recycleItemsSelection.setMaximumSize(new java.awt.Dimension(680, 310));
        recycleItemsSelection.setMinimumSize(new java.awt.Dimension(680, 310));
        recycleItemsSelection.setPreferredSize(new java.awt.Dimension(680, 310));

        itemTypeToRecycleSelectionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{" "}));

        itemTypeSlectionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itemTypeSlectionLabel.setText("Select Item To Recycle");

        enterWeightLabel.setText("Enter Weight to be deposited:");

        addMoreItemsButton.setText("Add More Items");
        addMoreItemsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMoreItemsButtonClick(evt);
            }
        });

        submitButton.setText("Submit ");
        submitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitSelectionButtonClick(evt);
            }
        });
        submitButton.addActionListener(evt -> submitButtonActionPerformed(evt));

        javax.swing.GroupLayout recycleItemsSelectionLayout = new javax.swing.GroupLayout(recycleItemsSelection);
        recycleItemsSelection.setLayout(recycleItemsSelectionLayout);
        recycleItemsSelectionLayout.setHorizontalGroup(
                recycleItemsSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recycleItemsSelectionLayout.createSequentialGroup()
                                .addGroup(recycleItemsSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(recycleItemsSelectionLayout.createSequentialGroup()
                                                .addGap(240, 240, 240)
                                                .addGroup(recycleItemsSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(itemTypeSlectionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(recycleItemsSelectionLayout.createSequentialGroup()
                                                                .addGap(20, 20, 20)
                                                                .addComponent(itemTypeToRecycleSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(recycleItemsSelectionLayout.createSequentialGroup()
                                                .addGap(125, 125, 125)
                                                .addComponent(enterWeightLabel)
                                                .addGap(44, 44, 44)
                                                .addComponent(enterWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(recycleItemsSelectionLayout.createSequentialGroup()
                                                .addGap(163, 163, 163)
                                                .addComponent(addMoreItemsButton)
                                                .addGap(76, 76, 76)
                                                .addComponent(submitButton)))
                                .addContainerGap(172, Short.MAX_VALUE))
        );
        recycleItemsSelectionLayout.setVerticalGroup(
                recycleItemsSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(recycleItemsSelectionLayout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(itemTypeSlectionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemTypeToRecycleSelectionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addGroup(recycleItemsSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(enterWeightLabel)
                                        .addComponent(enterWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(recycleItemsSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addMoreItemsButton)
                                        .addComponent(submitButton))
                                .addContainerGap(87, Short.MAX_VALUE))
        );

        bodyBodyPanel.add(recycleItemsSelection, "card4");

        showSelectedList.setBackground(new java.awt.Color(102, 204, 255));
        showSelectedList.setMaximumSize(new java.awt.Dimension(680, 310));
        showSelectedList.setMinimumSize(new java.awt.Dimension(680, 310));
        showSelectedList.setSize(new java.awt.Dimension(680, 310));

        showItemTypeTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                },
                new String[]{
                        "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jScrollPane1.setViewportView(showItemTypeTable);

        showInkgsButton.setText("Show in kgs");
        showInkgsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInKgsButtonClicked(evt);
            }
        });

        totalValueLabel.setText("Total Value:");

        addMoreItemsGoBack.setText("Add More Items");
        addMoreItemsGoBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMoreItemsGoBackButtonClick(evt);
            }
        });

        getRewardButton.setText("Get Reward");
        getRewardButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                getRewardButtonClicked(evt);
            }
        });

        showInLbsButton.setText("Show in Lbs");
        showInLbsButton.setMaximumSize(new java.awt.Dimension(120, 29));
        showInLbsButton.setMinimumSize(new java.awt.Dimension(120, 29));
        showInLbsButton.setPreferredSize(new java.awt.Dimension(120, 29));
        showInLbsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInLbsButtonClicked(evt);
            }
        });

        javax.swing.GroupLayout showSelectedListLayout = new javax.swing.GroupLayout(showSelectedList);
        showSelectedList.setLayout(showSelectedListLayout);
        showSelectedListLayout.setHorizontalGroup(
                showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                .addGroup(showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(totalValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(69, 69, 69)
                                                .addComponent(showTotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                                .addGroup(showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                                                .addGap(79, 79, 79)
                                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addComponent(addMoreItemsGoBack)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(getRewardButton)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(showInkgsButton)
                                                        .addComponent(showInLbsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap(22, Short.MAX_VALUE))
        );
        showSelectedListLayout.setVerticalGroup(
                showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                .addGroup(showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(showSelectedListLayout.createSequentialGroup()
                                                .addGap(56, 56, 56)
                                                .addComponent(showInkgsButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(showInLbsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(38, 38, 38)
                                .addGroup(showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalValueLabel)
                                        .addComponent(showTotalPriceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                .addGroup(showSelectedListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(addMoreItemsGoBack)
                                        .addComponent(getRewardButton))
                                .addGap(50, 50, 50))
        );

        bodyBodyPanel.add(showSelectedList, "card5");

        moneyCouponSelection.setBackground(new java.awt.Color(102, 204, 255));
        moneyCouponSelection.setMaximumSize(new java.awt.Dimension(680, 320));
        moneyCouponSelection.setMinimumSize(new java.awt.Dimension(680, 320));
        moneyCouponSelection.setPreferredSize(new java.awt.Dimension(680, 320));
        moneyCouponSelection.setSize(new java.awt.Dimension(680, 320));

        selectValueTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        selectValueTitle.setText("Select Money Or Coupon");

        totalPriceOfDroppedItemsTitle.setText("Total Price Of Dropped Items:");

        rewardSelection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"--Select Reward--", "Money", "GiftVoucher"}));
        rewardSelection.addItemListener(evt -> rewardSelectionItemStateChanged(evt));

        submitReward.setText("Submit Reward Selection");
        submitReward.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitRewardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout moneyCouponSelectionLayout = new javax.swing.GroupLayout(moneyCouponSelection);
        moneyCouponSelection.setLayout(moneyCouponSelectionLayout);
        moneyCouponSelectionLayout.setHorizontalGroup(
                moneyCouponSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(moneyCouponSelectionLayout.createSequentialGroup()
                                .addGroup(moneyCouponSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(moneyCouponSelectionLayout.createSequentialGroup()
                                                .addGap(188, 188, 188)
                                                .addComponent(selectValueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(moneyCouponSelectionLayout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addComponent(totalPriceOfDroppedItemsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(totalPriceOfDroppedItemsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(moneyCouponSelectionLayout.createSequentialGroup()
                                                .addGap(248, 248, 248)
                                                .addComponent(rewardSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(moneyCouponSelectionLayout.createSequentialGroup()
                                                .addGap(236, 236, 236)
                                                .addComponent(submitReward)))
                                .addContainerGap(125, Short.MAX_VALUE))
        );
        moneyCouponSelectionLayout.setVerticalGroup(
                moneyCouponSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(moneyCouponSelectionLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(selectValueTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rewardSelection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addGroup(moneyCouponSelectionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(totalPriceOfDroppedItemsTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalPriceOfDroppedItemsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(submitReward)
                                .addGap(45, 45, 45))
        );

        bodyBodyPanel.add(moneyCouponSelection, "card6");

        bodyPanel.add(bodyBodyPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(bodyPanel, java.awt.BorderLayout.CENTER);

        outputPanel.setBackground(new java.awt.Color(1, 87, 155));
        outputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", Font.PLAIN, 13), new java.awt.Color(204, 255, 255))); // NOI18N
        outputPanel.setMaximumSize(new java.awt.Dimension(560, 60));
        outputPanel.setMinimumSize(new java.awt.Dimension(560, 60));

        outputLabel.setForeground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
                outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 662, Short.MAX_VALUE)
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(outputPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(outputLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        outputPanelLayout.setVerticalGroup(
                outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 36, Short.MAX_VALUE)
                        .addGroup(outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(outputPanelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(outputLabel)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );

        mainPanel.add(outputPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        pack();
    }

    private void dashBoardButtonClicked(java.awt.event.MouseEvent evt) {
        removeAllPanels();
        dashBoardPanel.setVisible(true);
        initTable();
        outputLabel.setText("");
    }

    private void recycleItemsButtonClicked(java.awt.event.MouseEvent evt) {
        removeAllPanels();
        recycleItemsSelection.setVisible(true);
        itemTypeToRecycleSelectionBox.removeAllItems();
        rcmHelper.populateItemTypeList(itemTypeToRecycleSelectionBox);
    }

    private void addMoreItemsButtonClick(java.awt.event.MouseEvent evt) {

        Date date = new Date();
        RecyclableItemTransaction recyclableItemTransaction = new RecyclableItemTransactionBuilder()
                .withMachineId(machineId)
                .withItemType(ItemTypeEnum.valueOf(Objects.requireNonNull(itemTypeToRecycleSelectionBox.getSelectedItem()).toString()))
                .withItemWieght(Double.parseDouble(enterWeightField.getText()))
                .withTimestamp(date)
                .build();
        rcmHelper.addItemsInTransaction(outputLabel, recyclableItemTransaction, groupId, false);
        removeAllPanels();
        recycleItemsSelection.setVisible(true);
        itemTypeToRecycleSelectionBox.setSelectedIndex(0);
        enterWeightField.setText("");
        itemTypeToRecycleSelectionBox.removeAllItems();
        rcmHelper.populateItemTypeList(itemTypeToRecycleSelectionBox);
    }

    private void submitSelectionButtonClick(java.awt.event.MouseEvent evt) {

        Date date = new Date();
        if (enterWeightField.getText().length() > 0) {
            RecyclableItemTransaction recyclableItemTransaction = new RecyclableItemTransactionBuilder()
                    .withMachineId(machineId)
                    .withItemType(ItemTypeEnum.valueOf(Objects.requireNonNull(itemTypeToRecycleSelectionBox.getSelectedItem()).toString()))
                    .withItemWieght(Double.parseDouble(enterWeightField.getText()))
                    .withTimestamp(date)
                    .build();
            rcmHelper.addItemsInTransaction(outputLabel, recyclableItemTransaction, groupId, true);
            itemTypeToRecycleSelectionBox.setSelectedIndex(0);
            enterWeightField.setText("");
            removeAllPanels();
            showSelectedList.setVisible(true);
            rcmHelper.showSelectedItemTypeListLbs(showItemTypeTable);
            rcmHelper.setTotalPriceLabel(showTotalPriceLabel);
        } else {
            outputLabel.setText("Please enter weight field!!");
        }

    }

    private void showInKgsButtonClicked(java.awt.event.MouseEvent evt) {
        rcmHelper.showSelectedItemTypeListKgs(showItemTypeTable);
        showInkgsButton.setEnabled(true);
        showInLbsButton.setEnabled(false);
    }

    private void addMoreItemsGoBackButtonClick(java.awt.event.MouseEvent evt) {

        removeAllPanels();
        recycleItemsSelection.setVisible(true);
        itemTypeToRecycleSelectionBox.setSelectedIndex(0);
        enterWeightField.setText("");
        itemTypeToRecycleSelectionBox.removeAllItems();
        rcmHelper.populateItemTypeList(itemTypeToRecycleSelectionBox);
    }

    private void getRewardButtonClicked(java.awt.event.MouseEvent evt) {

        if (outputLabel.getText().equals("This machine is full ")) {
            rcmHelper.cancelTrasaction();
            removeAllPanels();
            welcomePanel.setVisible(true);
            welcomeLabel.setText(String.format("Welcome to %s", machineId));

        } else {
            removeAllPanels();
            moneyCouponSelection.setVisible(true);
            rcmHelper.setTotalPriceLabel(totalPriceOfDroppedItemsLabel);
        }
    }

    private void showInLbsButtonClicked(java.awt.event.MouseEvent evt) {
        rcmHelper.showSelectedItemTypeListLbs(showItemTypeTable);
        showInkgsButton.setEnabled(false);
        showInLbsButton.setEnabled(true);
    }

    private void submitRewardMouseClicked(java.awt.event.MouseEvent evt) {
        rcmHelper.getReward(rewardSelection);
        rcmHelper.submitTransactions(groupId);
        rcmHelper.clearAllData();
        removeAllPanels();
        welcomePanel.setVisible(true);
        welcomeLabel.setText(String.format("Welcome to %s", machineId));
        outputLabel.setText("");
    }

    private void rewardSelectionItemStateChanged(java.awt.event.ItemEvent evt) {
        rcmHelper.getRewardSelectionState(rewardSelection, outputLabel);
    }

    private void cancelAddingItemsButtonClick(java.awt.event.MouseEvent evt) {
        rcmHelper.cancelTrasaction();
        removeAllPanels();
        welcomePanel.setVisible(true);
        welcomeLabel.setText(String.format("Welcome to %s", machineId));
        outputLabel.setText("");
    }

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {

    }

}
